
-- =========================================================
-- NYTHERA – KOMPLETTE DATENBANK V4
-- In Supabase: SQL Editor -> New query -> alles einfügen -> Run
-- Bestehende Hauptdaten bleiben erhalten.
-- =========================================================

create extension if not exists pgcrypto;

-- 1) REGISTRIERUNGEN
create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  discord_id text,
  discord_user_id text,
  ingame_id text,
  first_name text,
  last_name text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by text
);

alter table public.registrations
  add column if not exists discord_id text,
  add column if not exists discord_user_id text,
  add column if not exists ingame_id text,
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists status text default 'pending',
  add column if not exists created_at timestamptz default now(),
  add column if not exists approved_at timestamptz,
  add column if not exists approved_by text;

update public.registrations
set discord_id = discord_user_id
where discord_id is null and discord_user_id is not null;

update public.registrations
set discord_user_id = discord_id
where discord_user_id is null and discord_id is not null;

alter table public.registrations alter column discord_user_id drop not null;

-- Unique indexes only when there are no duplicates.
do $$
begin
  if not exists (
    select 1 from public.registrations
    where discord_id is not null
    group by discord_id having count(*) > 1
  ) then
    create unique index if not exists registrations_discord_id_unique
      on public.registrations(discord_id) where discord_id is not null;
  end if;

  if not exists (
    select 1 from public.registrations
    where discord_user_id is not null
    group by discord_user_id having count(*) > 1
  ) then
    create unique index if not exists registrations_discord_user_id_unique
      on public.registrations(discord_user_id) where discord_user_id is not null;
  end if;
end $$;

-- 2) ABMELDUNGEN
create table if not exists public.absences (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  absence_type text not null,
  reason text not null,
  start_at timestamptz not null default now(),
  end_at timestamptz,
  status text not null default 'active',
  returned_at timestamptz,
  created_at timestamptz not null default now()
);

-- 3) EVENTS
create table if not exists public.event_templates (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  automatic boolean not null default false,
  start_times text[] not null default '{}',
  registration_minutes integer not null default 25,
  participant_limit integer not null default 25,
  discord_channel_id text,
  travel_payout bigint not null default 0,
  win_payout bigint not null default 0,
  kill_payout bigint not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.event_templates
  add column if not exists active boolean not null default true,
  add column if not exists automatic boolean not null default false,
  add column if not exists start_times text[] not null default '{}',
  add column if not exists registration_minutes integer not null default 25,
  add column if not exists participant_limit integer not null default 25,
  add column if not exists discord_channel_id text,
  add column if not exists travel_payout bigint not null default 0,
  add column if not exists win_payout bigint not null default 0,
  add column if not exists kill_payout bigint not null default 0,
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.event_runs (
  id bigint generated by default as identity primary key,
  template_id bigint,
  status text not null default 'registration_open',
  trigger text not null default 'manual',
  scheduled_start timestamptz,
  discord_channel_id text,
  discord_message_id text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz
);

alter table public.event_runs
  add column if not exists template_id bigint,
  add column if not exists status text not null default 'registration_open',
  add column if not exists trigger text not null default 'manual',
  add column if not exists scheduled_start timestamptz,
  add column if not exists discord_channel_id text,
  add column if not exists discord_message_id text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists started_at timestamptz,
  add column if not exists ended_at timestamptz;

create table if not exists public.event_participants (
  id bigint generated by default as identity primary key,
  run_id bigint not null,
  discord_id text not null,
  registration_id text,
  joined_at timestamptz not null default now()
);

alter table public.event_participants
  add column if not exists run_id bigint,
  add column if not exists discord_id text,
  add column if not exists registration_id text,
  add column if not exists joined_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from public.event_participants
    group by run_id, discord_id having count(*) > 1
  ) then
    create unique index if not exists event_participants_run_discord_unique
      on public.event_participants(run_id, discord_id);
  end if;
end $$;

-- 4) PANELS
-- Deine vorhandene panels.id ist UUID. Deshalb werden alle Panel-Verweise UUID.
create table if not exists public.panels (
  id uuid primary key default gen_random_uuid(),
  panel_number integer,
  assigned_discord_id text,
  owner_discord_id text,
  owner_name text,
  owner_ingame_id text,
  location text,
  status text not null default 'active',
  channel_id text,
  discord_message_id text,
  started_at timestamptz not null default now(),
  ends_at timestamptz,
  repairs_done integer not null default 0,
  collected_at timestamptz,
  collected_by text,
  collection_value bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.panels
  add column if not exists panel_number integer,
  add column if not exists assigned_discord_id text,
  add column if not exists owner_discord_id text,
  add column if not exists owner_name text,
  add column if not exists owner_ingame_id text,
  add column if not exists location text,
  add column if not exists status text not null default 'active',
  add column if not exists channel_id text,
  add column if not exists discord_message_id text,
  add column if not exists started_at timestamptz not null default now(),
  add column if not exists ends_at timestamptz,
  add column if not exists repairs_done integer not null default 0,
  add column if not exists collected_at timestamptz,
  add column if not exists collected_by text,
  add column if not exists collection_value bigint not null default 0,
  add column if not exists created_at timestamptz not null default now();

-- Diese beiden Hilfstabellen dürfen neu erstellt werden.
drop table if exists public.panel_notifications cascade;
drop table if exists public.panel_repairs cascade;

create table public.panel_repairs (
  id bigint generated by default as identity primary key,
  panel_id uuid not null references public.panels(id) on delete cascade,
  hour_number integer not null,
  repaired_by text not null,
  repaired_at timestamptz not null default now(),
  unique (panel_id, hour_number)
);

create table public.panel_notifications (
  id bigint generated by default as identity primary key,
  panel_id uuid not null references public.panels(id) on delete cascade,
  notification_key text not null unique,
  notification_type text not null,
  created_at timestamptz not null default now()
);

-- 5) AUSZAHLUNGEN / VERWARNUNGEN / AKTIONEN
create table if not exists public.payouts (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  amount bigint not null default 0,
  category text not null default 'manual',
  status text not null default 'open',
  created_by text,
  created_at timestamptz not null default now(),
  completed_by text,
  completed_at timestamptz
);

create table if not exists public.warnings (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  reason text not null,
  points integer not null default 1,
  status text not null default 'active',
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.member_actions (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  action_type text not null,
  reason text not null,
  start_at timestamptz not null default now(),
  end_at timestamptz,
  created_by text not null,
  delivery_status text not null default 'pending',
  acknowledged_at timestamptz,
  response_text text,
  created_at timestamptz not null default now()
);

-- 6) KILL-LOGS / KILL-TICKETS
create table if not exists public.kill_logs (
  id bigint generated by default as identity primary key,
  discord_id text,
  event_run_id bigint,
  victim_ref text,
  weapon text,
  source text not null default 'auto',
  verified boolean not null default false,
  payout_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.kill_tickets (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  registration_id text,
  event_run_id bigint,
  event_name text,
  victim_ref text,
  weapon text,
  evidence_url text,
  note text,
  status text not null default 'open',
  reviewed_by text,
  reviewed_at timestamptz,
  payout_id bigint,
  created_at timestamptz not null default now()
);

-- 7) BLOOD-IN / BLOOD-OUT / UNTERNEHMEN
create table if not exists public.blood_in (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  ingame_id text not null,
  discord_id text,
  invited_by text not null,
  invited_at timestamptz not null default now(),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.blood_out (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  ingame_id text not null,
  discord_id text,
  removed_by text not null,
  removed_at timestamptz not null default now(),
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  owner_name text,
  owner_discord_id text,
  note text,
  active boolean not null default true,
  created_by text not null,
  created_at timestamptz not null default now()
);

-- 8) SETUP / SYSTEM
create table if not exists public.system_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.channel_setup_log (
  id bigint generated by default as identity primary key,
  setup_type text not null,
  channel_id text not null,
  configured_by text not null,
  configured_at timestamptz not null default now()
);

create table if not exists public.automation_locks (
  id bigint generated by default as identity primary key,
  lock_key text not null unique,
  created_at timestamptz not null default now()
);

-- 9) EVENTS EINTRAGEN
insert into public.event_templates
(name,active,automatic,start_times,registration_minutes,participant_limit,travel_payout,win_payout,kill_payout,notes)
values
('40er',false,true,array['00:25','01:25','02:25','03:25','04:25','05:25','06:25','07:25','08:25','09:25','10:25','11:25','12:25','13:25','14:25','15:25','16:25','17:25','18:25','19:25','20:25','21:25','22:25','23:25'],15,25,0,0,0,'Stündlich um XX:25'),
('50er',true,true,array['20:25'],25,25,0,0,10000,null),
('Bizwar',true,true,array['00:40','18:40'],25,25,0,0,0,null),
('Einkaufszentrum',true,false,array[]::text[],15,25,0,0,0,null),
('Famwar',false,false,array[]::text[],25,25,0,0,0,null),
('Gießerei',true,true,array['13:55'],25,25,0,0,0,null),
('Hotel',false,true,array['01:55'],25,25,0,0,0,null),
('RP-Fabrik',true,true,array['10:15','16:15','22:15'],30,25,5000,30000,0,null),
('Staatliche-Kontrolle',true,false,array[]::text[],30,25,0,0,0,null),
('Waffenfabrik',true,true,array['02:55','06:55','09:55','21:55'],25,25,0,0,0,null),
('Weinberge',true,true,array['19:50'],25,25,0,15000,0,null)
on conflict (name) do update set
  active=excluded.active,
  automatic=excluded.automatic,
  start_times=excluded.start_times,
  registration_minutes=excluded.registration_minutes,
  participant_limit=excluded.participant_limit,
  travel_payout=excluded.travel_payout,
  win_payout=excluded.win_payout,
  kill_payout=excluded.kill_payout,
  notes=excluded.notes;

-- 10) CHANNEL-EINSTELLUNGEN
insert into public.system_settings(key,value)
values
('registration_channel_id','null'::jsonb),
('registration_review_channel_id','null'::jsonb),
('absence_channel_id','null'::jsonb),
('event_channel_id','null'::jsonb),
('panel_channel_id','null'::jsonb),
('payout_channel_id','null'::jsonb),
('kill_ticket_channel_id','null'::jsonb),
('live_channel_id','null'::jsonb),
('blood_in_channel_id','null'::jsonb),
('blood_out_channel_id','null'::jsonb),
('company_channel_id','null'::jsonb),
('timezone','"Africa/Johannesburg"'::jsonb),
('test_mode','true'::jsonb)
on conflict (key) do nothing;

-- 11) SUPABASE-CACHE AKTUALISIEREN
notify pgrst, 'reload schema';

-- 12) ABSCHLUSSPRÜFUNG
select table_name
from information_schema.tables
where table_schema='public'
and table_name in (
  'registrations','absences','event_templates','event_runs','event_participants',
  'panels','panel_repairs','panel_notifications','payouts','warnings',
  'member_actions','kill_logs','kill_tickets','blood_in','blood_out',
  'companies','system_settings','channel_setup_log','automation_locks'
)
order by table_name;
