-- Nythera Hotfix: Registrierung + Schema Cache
alter table public.registrations
  add column if not exists discord_id text,
  add column if not exists discord_user_id text;

update public.registrations
set discord_user_id = discord_id
where discord_user_id is null
  and discord_id is not null;

update public.registrations
set discord_id = discord_user_id
where discord_id is null
  and discord_user_id is not null;

-- Neue Registrierungen können beide Spalten nutzen.
alter table public.registrations
  alter column discord_user_id drop not null;

create unique index if not exists registrations_discord_id_unique
  on public.registrations(discord_id)
  where discord_id is not null;

create unique index if not exists registrations_discord_user_id_unique
  on public.registrations(discord_user_id)
  where discord_user_id is not null;

create table if not exists public.channel_setup_log (
  id bigint generated by default as identity primary key,
  setup_type text not null,
  channel_id text not null,
  configured_by text not null,
  configured_at timestamptz not null default now()
);

notify pgrst, 'reload schema';
